name: Auto Publish to PyPI on Data Update

on:
  repository_dispatch:
    types: [data_update_triggered]
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update data and publish to PyPI'
        required: false
        default: false
        type: boolean

jobs:
  auto-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests build twine

      - name: Log trigger reason and get external commit info
        id: external-commit
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            echo "Workflow triggered by external repository changes"
            if [ -n "${{ github.event.client_payload.trigger_reason }}" ]; then
              echo "Trigger reason: ${{ github.event.client_payload.trigger_reason }}"
            fi
            if [ -n "${{ github.event.client_payload.commit_sha }}" ]; then
              echo "External commit SHA: ${{ github.event.client_payload.commit_sha }}"
              echo "commit_sha=${{ github.event.client_payload.commit_sha }}" >> $GITHUB_OUTPUT
            fi
            if [ -n "${{ github.event.client_payload.commit_date }}" ]; then
              echo "External commit date: ${{ github.event.client_payload.commit_date }}"
            fi
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Workflow triggered manually (force update: ${{ github.event.inputs.force_update }})"
            
            # For manual updates, fetch the latest external commit info
            echo "Fetching latest external commit information..."
            LATEST_VENDOR_COMMIT=$(curl -s "https://api.github.com/repos/pkmn/randbats/commits?path=vendor&per_page=1" | jq -r '.[0].sha')
            
            if [ "$LATEST_VENDOR_COMMIT" != "null" ] && [ -n "$LATEST_VENDOR_COMMIT" ]; then
              echo "Latest external commit SHA: $LATEST_VENDOR_COMMIT"
              echo "commit_sha=$LATEST_VENDOR_COMMIT" >> $GITHUB_OUTPUT
            else
              echo "Could not fetch latest external commit SHA"
            fi
          fi

      - name: Run data update script
        run: |
          python scripts/update_all_data.py

      - name: Bump version and publish
        run: |
          # Read current version from pyproject.toml
          CURRENT_VERSION=$(grep '^version = ' pyproject.toml | cut -d'"' -f2)
          echo "Current version: $CURRENT_VERSION"
          
          # Split version into components
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          
          # Bump patch version
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo "New version: $NEW_VERSION"
          
          # Update version in pyproject.toml
          sed -i "s/^version = \"$CURRENT_VERSION\"/version = \"$NEW_VERSION\"/" pyproject.toml
          
          # Add all data files and version bump
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add localsets/randbattle_data/*.json localsets/metadata/*.json localsets/smogon_data/*.json pyproject.toml
          
          # Create commit message with external commit info if available
          COMMIT_MSG="chore: update data and bump version to $NEW_VERSION [auto]"
          EXTERNAL_COMMIT_SHA="${{ steps.external-commit.outputs.commit_sha }}"
          
          if [ -n "$EXTERNAL_COMMIT_SHA" ]; then
            COMMIT_MSG="chore: update data and bump version to $NEW_VERSION [auto] - triggered by pkmn/randbats commit $EXTERNAL_COMMIT_SHA"
          fi
          
          git commit -m "$COMMIT_MSG"
          
          # Create and push version tag
          git tag "v$NEW_VERSION"
          git push origin main
          git push origin "v$NEW_VERSION"
          
          echo "Version bumped to $NEW_VERSION and tag pushed"

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/* 