name: Data Directory Change Trigger

on:
  push:
    paths:
      - 'localsets/randbattle_data/**'
      - 'localsets/metadata/**'
      - 'localsets/smogon_data/**'

jobs:
  report-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: List changed files
        run: |
          echo "Changed files in data directories:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E 'localsets/(randbattle_data|metadata|smogon_data)/' 